### ISSUE TITLE
Urgent! How can i install miniconda under R environment by using reticulate?

### ISSUE THREAD

**Issue by jiangzh-coder** [rstudio/reticulate#1297]
Hi!  i tried to install miniconda under R environment by using reticulate, but i met some problems: (errors)

install.packages("reticulate")
library(reticulate)
reticulate::install_miniconda(force = TRUE)
......
Error: Error creating conda environment 'r-reticulate' [exit code 1]

Can anyone help me?

**Comment by t-kalinowski** [comment]
Hi, sorry you're having issues, I can try to help.

- Is that all the output shown, or was there other output you omitted? If there was other output, can you please provide it?
- What OS and platform are you on? If on Mac, are you on M1 or x86? Does your build of R match your CPU architecture or are you running R under Rosetta?
- Do you already have another conda or miniconda installed on your machine?
- Is this a fresh install of reticulate, or a re-install?
- You can try to reset all of reticulate's state with `reticulate:::rm_all_reticulate_state()` and see if that helps.

**Comment by t-kalinowski** [comment]
Is this related to https://github.com/rstudio/reticulate/pull/1287? 
You are correct @barryrowlingson, that fix is merged into dev main, but not released to CRAN yet.
Can you please confirm that installing the dev version fixes the issue for you and your students?
```r
remotes::install_github("rstudio/reticulate")
```

**Comment by barryrowlingson** [comment]
Thanks, but I am trying to persuade them to keep everything to CRAN-only for quality control reasons... I may have to give up that! Are there any blockers to getting a new release on CRAN?

**Comment by swmpkim** [comment]
I was having the same issue as @barryrowlingson 's students and am here because of that rstudio community forum post. Installing the dev version of `reticulate` fixed the error for me!

As background, I'm trying to reproduce someone else's code, so am otherwise unfamiliar with the package (and OpenSSL). Windows 10, x64.

And also, thanks for this helpful error message; it made the installation work easily.
```
> reticulate::install_miniconda()
Error: Miniconda is already installed at path "C:/.../r-miniconda".
- Use `reticulate::install_miniconda(force = TRUE)` to overwrite the previous installation.
```

**Comment by murmurrr** [comment]
I got the same problem and I tried all those ways above, still can't solve it. sad

**Comment by t-kalinowski** [comment]
@murmurrr Can you please open a new issue with instructions I can follow to reproduce the error?

**Comment by JoeJoe1313** [comment]
Hello @t-kalinowski, has this issue been resolved? I am facing the same problem now.

**Comment by t-kalinowski** [comment]
This issue has been resolved. If you're experiencing difficulties w/ conda today, please open a new issue and we can try to help. If you don't have a compelling need for conda, you can also use `reticulate::install_python()`, or install python using the official installers from python.org https://www.python.org/downloads/macos/
