### ISSUE TITLE
pandas > data frame conversion 'corrupt data frame' error

### ISSUE THREAD

**Issue by mdingemanse** [rstudio/reticulate#389]
On Windows 7, using R 3.5.1, Python 3.7.1, RStudio 1.2.1139, and reticulate_1.10.0.9003, running the toy example from the reticulate website results in a 'corrupt data frame' error. Not sure whether this is to do with type conversion or some other issue. Similar issue reported (for Windows, too) on StackOverflow [here](https://stackoverflow.com/questions/53445266/problem-with-reticulate-type-conversion-from-python-to-r-on-windows#comment93797472_53445266).

First a demonstration that the Python end of things works well via Reticulate:
```
Python 3.7.1 (conda\envs\r-reticulate\python.exe)
Reticulate 1.10.0.9003 REPL -- A Python interpreter in R.
>>> import pandas
>>> flights = pandas.read_csv("flights.csv",encoding="utf-8")
>>> flights = flights[flights['dest'] == 'ORD']
>>> flights = flights[['carrier', 'dep_delay', 'arr_delay']]
>>> flights = flights.dropna()
>>> print(flights.head())
   carrier  dep_delay  arr_delay
6       UA      227.0      219.0
17      AA        0.0      -19.0
20      UA       -3.0        7.0
22      UA       -3.0       -2.0
51      AA       -4.0      -28.0
>>> 
```
But if we try to reach the flights object in R we get this:

```
>>> quit
> py$flights %>% head()
                            carrier                         dep_delay
1 <environment: 0x000000001e25ce08> <environment: 0x000000001e3be750>
2                              <NA>                              <NA>
3                              <NA>                              <NA>
4                              <NA>                              <NA>
5                              <NA>                              <NA>
6                              <NA>                              <NA>
                          arr_delay
1 <environment: 0x000000001e51e178>
2                              <NA>
3                              <NA>
4                              <NA>
5                              <NA>
6                              <NA>
Warning message:
In format.data.frame(x, digits = digits, na.encode = FALSE) :
  corrupt data frame: columns will be truncated or padded with NAs
```

**Comment by kevinushey** [comment]
Can you provide a reproducible example? (I don't know what version of `flights.csv` you're using)

**Comment by mdingemanse** [comment]
Sorry — was using [this one](https://github.com/msamuel/hacks-pandas/blob/master/flights.csv) from another repo.

**Comment by kevinushey** [comment]
Doesn't work for me:

``` python
>>> import pandas
>>> flights = pandas.read_csv("flights.csv",encoding="utf-8")
>>> flights = flights[flights['dest'] == 'ORD']
KeyError: 'dest'
```

Can you provide a self-contained reproducible example?

**Comment by mdingemanse** [comment]
Python:
```{python}
import pandas as pd
d = {'A' : pd.Series([1., 2., 3.]), 'B' : pd.Series(['x', 'y', 'z'])}
df = pd.DataFrame(d)
print(df)
```
R:
```{r}
> py$df
                                  A                                 B
1 <environment: 0x0000000017b9ded0> <environment: 0x0000000017cc04f8>
2                              <NA>                              <NA>
3                              <NA>                              <NA>
Warning message:
In format.data.frame(x, digits = digits, na.encode = FALSE) :
  corrupt data frame: columns will be truncated or padded with NAs
> 
```

**Comment by mdingemanse** [comment]
Did that help — was it reproducible?

**Comment by kevinushey** [comment]
Sorry, no -- I'm still not able to reproduce. I didn't test in a conda environment though; this was just with a system Python install.

**Comment by grayskripko** [comment]
I got similar errors when I had the conda version of numpy

**Comment by kevinushey** [comment]
Thanks, I can reproduce with this. My best guess is that the class hierarchy has changed for categorical variables. We have a method for objects of class `pandas.core.categorical.Categorical`, but the class I see in this case is `pandas.core.arrays.categorical.Categorical`. I'll take a look next week.

**Comment by kevinushey** [comment]
I've committed a fix to master (it looks like it was fortunately a simple fix): https://github.com/rstudio/reticulate/commit/e2e408062b1146de8af519d836fef789df5f9693

Let me know if things work well in the development version of reticulate in your case. Use `devtools::install_github("rstudio/reticulate")` to install.

Thanks for the reproducible example!

**Comment by grayskripko** [comment]
it helped

**Comment by fmannhardt** [comment]
Thanks, it fixes the issue for me.

**Comment by sergiojsj76** [comment]
I still have the same error 

```
In format.data.frame(x, digits = digits, na.encode = FALSE) :
  corrupt data frame: columns will be truncated or padded with NAs
```

after updating reticulate to 1.10.0.9004. I have Python 3.7.1

**Comment by kevinushey** [comment]
@sergiojsj76 do you have a reproducible example? What code are you running?

**Comment by jrm87** [comment]
@kevinushey I have the same problem as @sergiojsj76 . 

I am using geopy in the function I am calling. The code in python is: 

```{r}
from geopy.geocoders import Nominatim
from geopy.extra.rate_limiter import RateLimiter
import pandas as pd

def loc(x):
    geolocator = Nominatim(user_agent="specify_your_app_name_here")
    df = pd.DataFrame(x, columns=['ad_vec'])
    geocode = RateLimiter(geolocator.geocode, min_delay_seconds=1)
    df['location'] = df['ad_vec'].apply(geocode)
    df['point'] = df['location'].apply(lambda loc: tuple(loc.point) if loc else None)

    return df
```

while the code in R is: 

```{r}
library(reticulate)
use_python('C:/Users/[user]/AppData/Local/Programs/Python/Python37', required=T)
source_python("[path]//test_address.py")
test_py<-loc(c("queens, NY","brooklyn"))
```

I get 

```
test_py
                             ad_vec                          location                             point
1 <environment: 0x000000001b01b3a8> <environment: 0x000000001b84a660> <environment: 0x000000001a962898>
2                              <NA>                              <NA>                              <NA>
Warning message:
In format.data.frame(x, digits = digits, na.encode = FALSE) :
  corrupt data frame: columns will be truncated or padded with NAs
```
Actually, R is handling the element test_py as a data.frame, with 2 ovs and 3 variables, as it should, but each variable is a numpy.ndarray, which I have not been able to transform into regular R data.frame. 

```
> class(test_py$ad_vec)
[1] "numpy.ndarray"         "python.builtin.object"
```

**Comment by LucaMingarelli** [comment]
Is there any news on this issue?

**Comment by t-kalinowski** [comment]
@LucaMingarelli (or any one else coming across this issue): the error described in this has been fixed. If you encountering a similar error, it likely is due to a different cause (much has changed since this issue was first opened 4 years ago). Please open a new issue, ideally with instructions we can follow to reproduce the error you are seeing.
